[platformio]
; Uncomment and set your proxy if needed
; proxy = http://www-proxy-ash7.us.oracle.com:80

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = no_ota.csv
monitor_speed = 115200
extra_scripts = pre:scripts/load_build_secrets.py
lib_deps =
  olikraus/U8g2 @ ^2.36.5
  h2zero/NimBLE-Arduino @ ^2.5.0
